-- PlanBridge Oracle DDL
-- Run as planbridge user

------------------------------------------------------
-- 0. 사용자 (JWT 인증 / RBAC)
------------------------------------------------------
CREATE TABLE PB_USER (
    USER_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    USERNAME        VARCHAR2(100)  NOT NULL,
    PASSWORD_HASH   VARCHAR2(255)  NOT NULL,
    ROLE            VARCHAR2(20)   DEFAULT 'DEVELOPER',   -- ADMIN / PLANNER / DEVELOPER
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PB_USER_USERNAME UNIQUE (USERNAME)
);

------------------------------------------------------
-- 1. 프로젝트
------------------------------------------------------
CREATE TABLE PB_PROJECT (
    PROJECT_ID      VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_NAME    VARCHAR2(200)  NOT NULL,
    PROJECT_DESC    VARCHAR2(4000),
    REPO_URL        VARCHAR2(500),
    REPO_LOCAL_PATH VARCHAR2(500),
    REPO_BRANCH     VARCHAR2(100)  DEFAULT 'main',
    REPO_TOKEN      VARCHAR2(500),
    BASE_URL        VARCHAR2(500),
    FRAMEWORK       VARCHAR2(50)   DEFAULT 'NEXTJS',
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    SYNC_STATUS     VARCHAR2(20)   DEFAULT 'IDLE',
    LAST_SYNCED_AT  TIMESTAMP,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

------------------------------------------------------
-- 2. 페이지 (Next.js 라우트 단위)
------------------------------------------------------
CREATE TABLE PB_PAGE (
    PAGE_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    ROUTE_PATH      VARCHAR2(500)  NOT NULL,
    PAGE_TITLE      VARCHAR2(200),
    FILE_PATH       VARCHAR2(500),
    LAYOUT_PATH     VARCHAR2(500),
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PB_PAGE UNIQUE (PROJECT_ID, ROUTE_PATH)
);

------------------------------------------------------
-- 3. 컴포넌트 (3-Layer Fingerprint, 자기참조 계층)
------------------------------------------------------
CREATE TABLE PB_COMPONENT (
    COMPONENT_ID    VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PAGE_ID         VARCHAR2(36)   NOT NULL REFERENCES PB_PAGE(PAGE_ID),
    PARENT_ID       VARCHAR2(36)   REFERENCES PB_COMPONENT(COMPONENT_ID),
    PB_ID           VARCHAR2(500)  NOT NULL,
    COMPONENT_NAME  VARCHAR2(200)  NOT NULL,
    CSS_SELECTOR    VARCHAR2(2000),
    COMPONENT_TYPE  VARCHAR2(30)   NOT NULL,
    ELEMENT_TAG     VARCHAR2(50),
    ELEMENT_ROLE    VARCHAR2(100),
    CURRENT_PROPS   CLOB,
    CURRENT_TEXT    VARCHAR2(4000),
    CURRENT_SPEC    CLOB,
    DEPTH_LEVEL     NUMBER(3)      DEFAULT 0,
    SORT_ORDER      NUMBER(5)      DEFAULT 0,
    TREE_PATH       VARCHAR2(2000),
    REACT_HIERARCHY CLOB,
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PB_COMPONENT UNIQUE (PAGE_ID, PB_ID)
);

CREATE INDEX IDX_PB_COMP_PARENT  ON PB_COMPONENT(PARENT_ID);
CREATE INDEX IDX_PB_COMP_PAGE    ON PB_COMPONENT(PAGE_ID);
CREATE INDEX IDX_PB_COMP_PBID    ON PB_COMPONENT(PB_ID);
CREATE INDEX IDX_PB_COMP_NAME    ON PB_COMPONENT(COMPONENT_NAME);
CREATE INDEX IDX_PB_COMP_TREE    ON PB_COMPONENT(TREE_PATH);

------------------------------------------------------
-- 4. 변경 요청
------------------------------------------------------
CREATE TABLE PB_CHANGE_REQUEST (
    REQUEST_ID      VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    COMPONENT_ID    VARCHAR2(36)   NOT NULL REFERENCES PB_COMPONENT(COMPONENT_ID),
    REQUESTED_BY    VARCHAR2(100)  NOT NULL,
    TITLE           VARCHAR2(500)  NOT NULL,
    DESCRIPTION     CLOB           NOT NULL,
    CURRENT_STATE   CLOB,
    DESIRED_STATE   CLOB,
    AI_ANALYSIS     CLOB,
    PRIORITY        VARCHAR2(20)   DEFAULT 'MEDIUM',
    STATUS          VARCHAR2(20)   DEFAULT 'DRAFT',
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_CR_COMPONENT ON PB_CHANGE_REQUEST(COMPONENT_ID);
CREATE INDEX IDX_PB_CR_STATUS    ON PB_CHANGE_REQUEST(STATUS);

------------------------------------------------------
-- 5. TODO 아이템 (AI 생성 태스크)
------------------------------------------------------
CREATE TABLE PB_TODO_ITEM (
    TODO_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    REQUEST_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_CHANGE_REQUEST(REQUEST_ID),
    TITLE           VARCHAR2(500)  NOT NULL,
    PROMPT          CLOB           NOT NULL,
    TARGET_FILES    CLOB,
    COMPLEXITY      VARCHAR2(20)   DEFAULT 'MODERATE',
    SORT_ORDER      NUMBER(3)      DEFAULT 0,
    DEPENDENCIES    VARCHAR2(500),
    STATUS          VARCHAR2(20)   DEFAULT 'PENDING',
    TEST_RESULT     CLOB,
    COMPLETED_BY    VARCHAR2(100),
    COMPLETED_AT    TIMESTAMP,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_TODO_REQUEST ON PB_TODO_ITEM(REQUEST_ID);

------------------------------------------------------
-- 6. 정책
------------------------------------------------------
CREATE TABLE PB_POLICY (
    POLICY_ID       VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    SCOPE           VARCHAR2(20)   NOT NULL,
    PAGE_ID         VARCHAR2(36)   REFERENCES PB_PAGE(PAGE_ID),
    COMPONENT_ID    VARCHAR2(36)   REFERENCES PB_COMPONENT(COMPONENT_ID),
    POLICY_TYPE     VARCHAR2(30)   NOT NULL,
    POLICY_TITLE    VARCHAR2(500)  NOT NULL,
    POLICY_CONTENT  CLOB           NOT NULL,
    POLICY_SCHEMA   CLOB,
    TAGS            VARCHAR2(2000),
    CURRENT_VERSION NUMBER(5)      DEFAULT 1,
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR2(100)  NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_BY      VARCHAR2(100),
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_POLICY_PROJECT   ON PB_POLICY(PROJECT_ID);
CREATE INDEX IDX_PB_POLICY_TYPE      ON PB_POLICY(POLICY_TYPE);
CREATE INDEX IDX_PB_POLICY_COMPONENT ON PB_POLICY(COMPONENT_ID);

------------------------------------------------------
-- 7. 정책 버전 이력
------------------------------------------------------
CREATE TABLE PB_POLICY_VERSION (
    VERSION_ID      VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    POLICY_ID       VARCHAR2(36)   NOT NULL REFERENCES PB_POLICY(POLICY_ID),
    VERSION_NO      NUMBER(5)      NOT NULL,
    POLICY_CONTENT  CLOB           NOT NULL,
    POLICY_SCHEMA   CLOB,
    CHANGE_REASON   VARCHAR2(2000),
    REQUEST_ID      VARCHAR2(36),
    CREATED_BY      VARCHAR2(100)  NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_PV_POLICY ON PB_POLICY_VERSION(POLICY_ID);

------------------------------------------------------
-- 8. 정책 연결 (컴포넌트 ↔ 정책)
------------------------------------------------------
CREATE TABLE PB_POLICY_LINK (
    LINK_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    POLICY_ID       VARCHAR2(36)   NOT NULL REFERENCES PB_POLICY(POLICY_ID),
    COMPONENT_ID    VARCHAR2(36)   NOT NULL REFERENCES PB_COMPONENT(COMPONENT_ID),
    LINK_TYPE       VARCHAR2(30)   DEFAULT 'APPLIED',
    OVERRIDE_CONTENT CLOB,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PB_POLICY_LINK UNIQUE (POLICY_ID, COMPONENT_ID)
);

------------------------------------------------------
-- 9. 스캔 이력
------------------------------------------------------
CREATE TABLE PB_SCAN_HISTORY (
    SCAN_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    PAGE_ID         VARCHAR2(36)   REFERENCES PB_PAGE(PAGE_ID),
    SCAN_TYPE       VARCHAR2(30)   NOT NULL,
    COMPONENT_COUNT NUMBER(7),
    NEW_COUNT       NUMBER(7)      DEFAULT 0,
    CHANGED_COUNT   NUMBER(7)      DEFAULT 0,
    REMOVED_COUNT   NUMBER(7)      DEFAULT 0,
    STATUS          VARCHAR2(20)   DEFAULT 'COMPLETED',
    SCANNED_BY      VARCHAR2(100),
    SCANNED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_SCAN_PROJECT ON PB_SCAN_HISTORY(PROJECT_ID);

------------------------------------------------------
-- 10. AI 분석 큐
------------------------------------------------------
CREATE TABLE PB_ANALYSIS_QUEUE (
    QUEUE_ID        VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    ANALYSIS_TYPE   VARCHAR2(30)   NOT NULL,
    REQUEST_ID      VARCHAR2(36),
    REQUEST_PAYLOAD CLOB           NOT NULL,
    STATUS          VARCHAR2(20)   DEFAULT 'QUEUED',
    WORKER_ID       VARCHAR2(100),
    RESULT          CLOB,
    ERROR_MESSAGE   VARCHAR2(4000),
    RETRY_COUNT     NUMBER(3)      DEFAULT 0,
    MAX_RETRIES     NUMBER(3)      DEFAULT 3,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    STARTED_AT      TIMESTAMP,
    COMPLETED_AT    TIMESTAMP
);

CREATE INDEX IDX_PB_AQ_STATUS  ON PB_ANALYSIS_QUEUE(STATUS);
CREATE INDEX IDX_PB_AQ_PROJECT ON PB_ANALYSIS_QUEUE(PROJECT_ID);

------------------------------------------------------
-- 11. Git 동기화 로그
------------------------------------------------------
CREATE TABLE PB_GIT_SYNC_LOG (
    SYNC_LOG_ID     VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    TRIGGER_TYPE    VARCHAR2(20)   NOT NULL,
    COMMIT_HASH     VARCHAR2(40),
    COMMIT_MESSAGE  VARCHAR2(1000),
    BRANCH          VARCHAR2(100),
    FILES_CHANGED   NUMBER(7),
    STATUS          VARCHAR2(20)   DEFAULT 'SUCCESS',
    ERROR_MESSAGE   VARCHAR2(4000),
    SYNCED_AT       TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_GSL_PROJECT ON PB_GIT_SYNC_LOG(PROJECT_ID);

------------------------------------------------------
-- 12. 화면 기획서
------------------------------------------------------
CREATE TABLE PB_SCREEN_PLAN (
    PLAN_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    PLAN_TITLE      VARCHAR2(500)  NOT NULL,
    ROUTE_PATH      VARCHAR2(500),
    DESCRIPTION     CLOB,
    WIREFRAME_JSON  CLOB,
    FULL_SPEC       CLOB,
    AI_SUGGESTION   CLOB,
    STATUS          VARCHAR2(20)   DEFAULT 'DRAFT',
    PAGE_ID         VARCHAR2(36)   REFERENCES PB_PAGE(PAGE_ID),
    CREATED_BY      VARCHAR2(100)  NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);
CREATE INDEX IDX_PB_PLAN_PROJECT ON PB_SCREEN_PLAN(PROJECT_ID, STATUS);

------------------------------------------------------
-- 13. 컴포넌트 스냅샷
------------------------------------------------------
CREATE TABLE PB_COMPONENT_SNAPSHOT (
    SNAPSHOT_ID     VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    COMPONENT_ID    VARCHAR2(36)   NOT NULL REFERENCES PB_COMPONENT(COMPONENT_ID),
    SCAN_HISTORY_ID VARCHAR2(36)   REFERENCES PB_SCAN_HISTORY(SCAN_ID),
    PROPS_JSON      CLOB,
    RECT_JSON       CLOB,
    SCREENSHOT_URL  VARCHAR2(500),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_CS_COMPONENT ON PB_COMPONENT_SNAPSHOT(COMPONENT_ID);
CREATE INDEX IDX_PB_CS_SCAN      ON PB_COMPONENT_SNAPSHOT(SCAN_HISTORY_ID);

------------------------------------------------------
-- 14. 기획서-정책 연결
------------------------------------------------------
CREATE TABLE PB_PLAN_POLICY (
    LINK_ID         VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PLAN_ID         VARCHAR2(36)   NOT NULL REFERENCES PB_SCREEN_PLAN(PLAN_ID),
    POLICY_ID       VARCHAR2(36)   NOT NULL REFERENCES PB_POLICY(POLICY_ID),
    LINK_NOTE       VARCHAR2(500),
    CREATED_BY      VARCHAR2(100),
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    CONSTRAINT UK_PB_PLAN_POLICY UNIQUE (PLAN_ID, POLICY_ID)
);

CREATE INDEX IDX_PB_PP_PLAN   ON PB_PLAN_POLICY(PLAN_ID);
CREATE INDEX IDX_PB_PP_POLICY ON PB_PLAN_POLICY(POLICY_ID);

------------------------------------------------------
-- 15. 테스트 체크리스트
------------------------------------------------------
CREATE TABLE PB_TEST_CHECKLIST (
    CHECKLIST_ID    VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    POLICY_ID       VARCHAR2(36)   REFERENCES PB_POLICY(POLICY_ID),
    PLAN_ID         VARCHAR2(36)   REFERENCES PB_SCREEN_PLAN(PLAN_ID),
    CHECKLIST_TITLE VARCHAR2(500)  NOT NULL,
    CHECKLIST_CONTENT CLOB,
    CHECK_TYPE      VARCHAR2(50)   DEFAULT 'MANUAL',
    STATUS          VARCHAR2(20)   DEFAULT 'PENDING',
    CHECKED_BY      VARCHAR2(100),
    CHECKED_AT      TIMESTAMP,
    CREATED_BY      VARCHAR2(100)  NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_TC_POLICY ON PB_TEST_CHECKLIST(POLICY_ID);
CREATE INDEX IDX_PB_TC_PLAN   ON PB_TEST_CHECKLIST(PLAN_ID);
CREATE INDEX IDX_PB_TC_STATUS ON PB_TEST_CHECKLIST(STATUS);

------------------------------------------------------
-- 16. 검증 룰
------------------------------------------------------
CREATE TABLE PB_VALIDATION_RULE (
    RULE_ID       VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    POLICY_ID     VARCHAR2(36)   NOT NULL REFERENCES PB_POLICY(POLICY_ID),
    RULE_TYPE     VARCHAR2(50)   NOT NULL,
    FIELD_NAME    VARCHAR2(200),
    RULE_VALUE    VARCHAR2(500),
    ERROR_MESSAGE VARCHAR2(500),
    SORT_ORDER    NUMBER(3)      DEFAULT 0,
    CREATED_AT    TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_VR_POLICY ON PB_VALIDATION_RULE(POLICY_ID);

------------------------------------------------------
-- 17. 컴포넌트 템플릿
------------------------------------------------------
CREATE TABLE PB_COMPONENT_TEMPLATE (
    TEMPLATE_ID     VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
    PROJECT_ID      VARCHAR2(36)   NOT NULL REFERENCES PB_PROJECT(PROJECT_ID),
    TEMPLATE_NAME   VARCHAR2(200)  NOT NULL,
    COMPONENT_TYPE  VARCHAR2(30)   NOT NULL,
    DESCRIPTION     VARCHAR2(1000),
    TEMPLATE_JSON   CLOB,
    POLICY_TAGS     VARCHAR2(500),
    USAGE_COUNT     NUMBER(7)      DEFAULT 0,
    STATUS          VARCHAR2(20)   DEFAULT 'ACTIVE',
    CREATED_BY      VARCHAR2(100)  NOT NULL,
    CREATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP,
    UPDATED_AT      TIMESTAMP      DEFAULT SYSTIMESTAMP
);

CREATE INDEX IDX_PB_CT_PROJECT ON PB_COMPONENT_TEMPLATE(PROJECT_ID);
CREATE INDEX IDX_PB_CT_STATUS  ON PB_COMPONENT_TEMPLATE(STATUS);
